elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
  container_name: es
  environment:
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
    memlock:
      soft: -1
      hard: -1
  volumes:
    - /mnt/ssd/esdata:/usr/share/elasticsearch/data
  ports:
    - 9200:9200
    - 9300:9300
